//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("authors")
export class authorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
name: string;

@Column({nullable: true})
books: string;


}
