//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Employees")
export class EmployeesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
employeeID: string;

@Column({nullable: true})
firstName: string;

@Column({nullable: true})
lastName: string;

@Column({nullable: true})
middleName: string;

@Column({nullable: true})
dateOfBirth: string;

@Column({nullable: true})
gender: string;

@Column({nullable: true})
nationality: string;

@Column({nullable: true})
maritalStatus: string;

@Column({nullable: true})
contactInformation: string;

@Column({nullable: true})
address: string;

@Column({nullable: true})
departmentTeam: string;

@Column({nullable: true})
positionRole: string;

@Column({nullable: true})
managerSupervisor: string;

@Column({nullable: true})
employmentType: string;

@Column({nullable: true})
startDate: string;

@Column({nullable: true})
endDate: string;

@Column({nullable: true})
salaryInformation: string;

@Column({nullable: true})
profilePicture: string;


}
