//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Evaluations")
export class EvaluationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
reviewID: string;

@Column({nullable: true})
employeeID: string;

@Column({nullable: true})
period: string;

@Column({nullable: true})
goalsObjectives: string;

@Column({nullable: true})
achievements: string;

@Column({nullable: true})
improvementAreas: string;

@Column({nullable: true})
feedbackFromSupervisor: string;

@Column({nullable: true})
overallRating: string;

@Column({nullable: true})
recommendations: string;


}
