//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("genres")
export class genresEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
category: string;


}
