//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Inventory")
export class InventoryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
userId: string;

@Column("text",{nullable: true})
cardId: string;

@Column("date",{nullable: true})
recordedDate: Date;


}
