//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("LeaveRequests")
export class LeaveRequestsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
requestID: string;

@Column({nullable: true})
employeeID: string;

@Column({nullable: true})
typeOfLeave: string;

@Column({nullable: true})
startDate: string;

@Column({nullable: true})
endDate: string;

@Column({nullable: true})
reason: string;

@Column({nullable: true})
approvalStatus: string;

@Column({nullable: true})
approverUserID: string;


}
