//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Sets")
export class SetsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
setId: string;

@Column("text",{nullable: true})
setname: string;

@Column("date",{nullable: true})
releasedate: Date;

@Column("integer",{nullable: true})
totalcards: number;


}
