// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Sets")
export class SetsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
SetName: string;

@Column("date",{nullable: true})
ReleaseDate: Date;

@Column("integer",{nullable: true})
TotalCards: number;


}
