// Source code generated by AppGPT (www.appgpt.tech)

import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from "react-admin";
import { useRecordContext } from "react-admin";
import { Grid } from "@mui/material";
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = "********";

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const setsTitle = () => {
  const record = useRecordContext();
  return <span>sets {record ? `"${record.setname}"` : ""}</span>;
};

export const setsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="setname" />
      <DateField source="releasedate" />
      <NumberField source="totalcards" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const setsEdit = () => (
  <Edit title={<setsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="setname" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="releasedate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalcards" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const setsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="setname" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="releasedate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalcards" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
];
