// Source code generated by AppGPT (www.appgpt.tech)

let data: any = {
  defaultData: {
    Users: [
      { UserName: "Ash Ketchum", email: "ash@pokemonworld.com" },
      { UserName: "Brock", email: "brock@pokemonworld.com" },
      { UserName: "Misty", email: "misty@pokemonworld.com" },
    ],
    Cards: [
      {
        CardName: "Pikachu",
        serial: "001",
        type: "Electric",
        rarity: "Common",
        condition: "Mint",
        imageurl: "pikachu.com",
        set: "Base Set",
      },
      {
        CardName: "Charizard",
        serial: "002",
        type: "Fire",
        rarity: "Rare",
        condition: "Near Mint",
        imageurl: "charizard.com",
        set: "Evolution Set",
      },
      {
        CardName: "Blastoise",
        serial: "003",
        type: "Water",
        rarity: "Uncommon",
        condition: "Good",
        imageurl: "blastoise.com",
        set: "Fossil Set",
      },
    ],
    Sets: [
      { SetName: "Base Set", ReleaseDate: "1999-01-09", TotalCards: "102" },
      {
        SetName: "Evolution Set",
        ReleaseDate: "2016-11-02",
        TotalCards: "108",
      },
      { SetName: "Fossil Set", ReleaseDate: "1999-10-10", TotalCards: "62" },
    ],
    Inventory: [
      { user: "Ash Ketchum", card: "Pikachu", RecordedDate: "2021-01-01" },
      { user: "Brock", card: "Charizard", RecordedDate: "2021-02-01" },
      { user: "Misty", card: "Blastoise", RecordedDate: "2021-03-01" },
    ],
    Wishlist: [
      { user: "Ash Ketchum", card: "Charizard", InsertedDate: "2021-04-01" },
      { user: "Brock", card: "Blastoise", InsertedDate: "2021-05-01" },
      { user: "Misty", card: "Pikachu", InsertedDate: "2021-06-01" },
    ],
  },
};
export default data;
