// Source code generated by AppGPT (www.appgpt.tech)

// in i18nProvider.js
import { mergeTranslations } from "ra-core";
import polyglotI18nProvider from "ra-i18n-polyglot";
import enOriginal from "ra-language-english";
import frOriginal from "ra-language-french";

const enResources = {
  resources: {
    users: {
      name: "users",
      fields: { username: "username", email: "email", id: "id" },
    },
    cards: {
      name: "cards",
      fields: {
        cardname: "card name",
        serial: "serial",
        type: "type",
        rarity: "rarity",
        condition: "condition",
        imageurl: "image url",
        set: "set",
        id: "id",
      },
    },
    sets: {
      name: "sets",
      fields: {
        setname: "set name",
        releasedate: "release date",
        totalcards: "total cards",
        id: "id",
      },
    },
    inventory: {
      name: "inventory",
      fields: {
        user: "user",
        card: "card",
        recordeddate: "recorded date",
        id: "id",
      },
    },
    wishlist: {
      name: "wishlist",
      fields: {
        user: "user",
        card: "card",
        inserteddate: "inserted date",
        id: "id",
      },
    },
  },
};
const frResources = {
  resources: {
    users: {
      name: "utilisateurs",
      fields: { username: "nom d'utilisateur", email: "email", id: "id" },
    },
    cards: {
      name: "cartes",
      fields: {
        cardname: "nom de la carte",
        serial: "série",
        type: "type",
        rarity: "rareté",
        condition: "condition",
        imageurl: "url de l'image",
        set: "ensemble",
        id: "id",
      },
    },
    sets: {
      name: "ensembles",
      fields: {
        setname: "nom de l'ensemble",
        releasedate: "date de sortie",
        totalcards: "total des cartes",
        id: "id",
      },
    },
    inventory: {
      name: "inventaire",
      fields: {
        user: "utilisateur",
        card: "carte",
        recordeddate: "date enregistrée",
        id: "id",
      },
    },
    wishlist: {
      name: "liste de souhaits",
      fields: {
        user: "utilisateur",
        card: "carte",
        inserteddate: "date insérée",
        id: "id",
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  "en", //default locale
  [
    { locale: "en", name: "English" },
    { locale: "fr", name: "Français" },
  ],
);
